# Don't print a new line at the start of the prompt
add_newline = false


format = """
$username\
$hostname\
$directory\
$cmd_duration\
$gcloud\
$kubernetes\
$python
$character"""

right_format = """
$git_branch\
$git_status\
$git_state"""

[username]
style_user = "bold red"
style_root = "black bold"
format = "[$user]($style)"
disabled = true

[hostname]
ssh_only = false
format = "[@$hostname](bold red) "
disabled = true

[directory]
format="[ $path]($style)[$read_only]($read_only_style) "
truncation_length = 8
truncation_symbol="…"
fish_style_pwd_dir_length=1
style = "blue"
read_only=" "
read_only_style="red"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
symbol=""
format = "[$symbol $branch]($style)"
style = "bright-black"
truncation_length=20

[git_status]
format = "|[[($all_status)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "✖$count"
ahead = "↑$count"
behind = "↓$count"
diverged = "⇕"
up_to_date = "✓"
untracked = "…$count"
stashed = "⚑$count"
modified = "+$count"
staged = '[●$count](green)'
renamed = "»$count"
deleted = "-$count"


[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
min_time = 5000

[python]
symbol=""
version_format="v$major.$minor"
format = '[\[${symbol} (${version} )(\($virtualenv\) )\]]($style)'
style = "bright-black"
detect_extensions = []
detect_files = []

[kubernetes]
symbol="☸"
format = '[\[$symbol$context\($namespace\)\]]($style) '
style = "dimmed blue"
disabled = false
contexts = [
    { context_pattern = "gke_.*_(?P<var_cluster>[\\w-]+)", context_alias = "$var_cluster"}
]

[gcloud]
symbol=""
format = '[\[$symbol $project\]]($style) '
style = "dimmed white"
disabled = false

[gcloud.project_aliases]
staging-266717 = "staging"
full-stack-259515 = "prod"
machine-learning-259515 = "ml"
